### ISSUE TITLE
Q: how to use?

### ISSUE THREAD

**Issue by boelle** [kemitchell/CC-BY-NC-SA-4.0#1]
how would i use this on my github project? their list of license options do not include a non commercial option

i know there is a debate on how bad it is but i do not want people to make money of my work

**Comment by kemitchell** [comment]
This is just a convenience repo for me, so I have quick access to the plain text version of [Creative Commons](https://creativecommons.org)' license.

This is _not_ a place for [legal advice](https://notlegaladvice.law). If you're interested in noncommercial licenses for software, I'd suggest you look into [PolyForm Noncommercial](https://polyformproject.org/licenses/noncommercial/1.0.0/) and [Prosperity](https://prosperitylicense.com).

**Comment by boelle** [comment]
its for hardware and i was not asking for legal advide

but i figured it all out
